---
- name: Create a 4096-bit SSH key for user root in /root/.ssh/id_rsa
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: '{{ ansible_hostname }}'
  when: ansible_hostname|lower == 'ct-i-c0'
  tags:
    - ssh
    - base