---
- name: Upgrade redhat System
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  become: yes
  when: ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos'
  tags:
    - update

- name: Update debian System (equivalent of "apt-get update")
  apt:
    update_cache: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - update

- name: Upgrade debian System
  apt:
    upgrade: dist
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - update

- name: Install Bash Completion for redhat System
  yum:
    name: bash-completion
    state: latest
  become: yes
  when: ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos'
  tags:
    - bash

- name: Install Bash Completion for debian System
  apt:
    name: bash-completion
    state: latest
    update_cache: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - bash

- name: Install Development Tools for redhat System
  yum:
    name: '@Development Tools'
    state: present
  become: yes
  when: ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos'
  tags:
    - development

- name: Install Build Essential for debian System
  apt:
    name: build-essential
    state: latest
    update_cache: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - development

- name: Install tmux for redhat System
  yum:
    name: tmux
    state: latest
  become: yes
  when: ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos'
  tags:
    - tmux

- name: Install tmux for debian System
  apt:
    name: tmux
    state: latest
    update_cache: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - bash

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - clean

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'
  tags:
    - clean